conditions: v1

git:
  depth: false

language: python

dist: xenial
cache: pip

before_install:
- pip install --upgrade pip flit

.mixtures:
- &install-and-test-blurb
  if: tag IS NOT present OR tag =~ ^blurb\-v\d+\.\d+\.\d+$
  install:
  - &cd-to-project pushd blurb
  - flit install
  - popd
  script:
  - blurb test

jobs:
  include:
  - python: "3.6"
    <<: *install-and-test-blurb
  - python: "3.7"
    <<: *install-and-test-blurb
  - python: "3.8"
    <<: *install-and-test-blurb
  - python: "3.9"
    <<: *install-and-test-blurb
